### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by raviapatel** [woodem/woo#31] opened 2020-12-08 10:49 UTC
Hi Vaclav,
I am trying to compile woodem can you tell me were is the compilation instructions or script which can be run on fresh ubuntu 20.04 virtual machine.
regards
Ravi

**Comment by eudoxos** [comment] 2020-12-08 15:57
Hi Ravi, sorry for the information not being completely up-to-date perhaps. The best might be to look at [.travis.yml](https://github.com/woodem/woo/blob/master/.travis.yml) which defines the build for continuous integration. I would just advise for the moment to say `-DWOO_PYBIND11=0` and to compile with boost::python instead, as there is some functionality still missing in the pybind11 build (that is why the CI test [like this one](https://travis-ci.org/github/woodem/woo/builds/737927413) fail).

**Comment by eudoxos** [comment] 2020-12-09 10:09
Hi Ravi, you pushed me to look again at the remaining issue with pybind11. This made it possible to ditch boost::python which is no longer supported. You can now follow the same building procedure as in Travis, including `WOO_PYBIND11=1` (which is now the default and mandatory, anyway). Best, Vaclav

**Comment by raviapatel** [comment] 2020-12-09 10:18
Thanks Vaclav,
I will now try to pull it an follow installation. I can try to push the build.sh script which works for me once i have figured out build process incase you want to include it in the source. 
Anyways for one project we plan to use woo quite a bit and we want to also implement some new contact laws. So I will contact you by email for that.
regards
Ravi

**Comment by raviapatel** [comment] 2020-12-09 11:50
Hi Vaclav,
So I did compile woo without error but i get error while importing now as below...

Traceback (most recent call last):
  File "/home/dem/.local/bin/woo", line 2, in <module>
    import wooMain,sys; sys.exit(wooMain.main())
  File "/home/dem/.local/lib/python3.8/site-packages/wooMain.py", line 288, in main
    import woo
  File "/home/dem/.local/lib/python3.8/site-packages/woo/__init__.py", line 317, in <module>
    from . import system
  File "/home/dem/.local/lib/python3.8/site-packages/woo/system.py", line 10, in <module>
    from woo._customConverters import *
ModuleNotFoundError: No module named 'woo._customConverters'
Stack trace (most recent call last):
#9    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#8    Object "/usr/bin/python3", at 0x5fa4dd, in _start
#7    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fdff9b1b0b9, in __libc_start_main
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fdff9b3dbdf, in exit
#5    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fdff9b3da26, in 
#4    Object "/home/dem/.local/lib/python3.8/site-packages/woo/_cxxInternal.cpython-38-x86_64-linux-gnu.so", at 0x7fdff7477068, in 
#3    Object "/home/dem/.local/lib/python3.8/site-packages/woo/_cxxInternal.cpython-38-x86_64-linux-gnu.so", at 0x7fdff76c9ffa, in std::_Function_base::_Base_manager<woo::AttrTrait<4>::ini<std::shared_ptr<woo::Plot>, (void*)0>(std::shared_ptr<woo::Plot>)::{lambda()#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<woo::AttrTrait<4>::ini<std::shared_ptr<woo::Plot>, (void*)0>(std::shared_ptr<woo::Plot>)::{lambda()#1}> const&, std::_Manager_operation)
#2    Object "/home/dem/.local/lib/python3.8/site-packages/woo/_cxxInternal.cpython-38-x86_64-linux-gnu.so", at 0x7fdff7402d17, in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
#1    Object "/home/dem/.local/lib/python3.8/site-packages/woo/_cxxInternal.cpython-38-x86_64-linux-gnu.so", at 0x7fdff76407e4, in 
#0    Object "/usr/bin/python3", at 0x5aee19, in 
Segmentation fault (Address not mapped to object [0xb8])
Segmentation fault (core dumped)

**Comment by eudoxos** [comment] 2020-12-09 11:52
The build uses cmake and is fairly standard. Don't try to use `setup.py` (to be deleted) or SCons (removed already).

**Comment by eudoxos** [comment] 2020-12-09 11:54
> ModuleNotFoundError: No module named 'woo._customConverters'

Oh yes, I just pushed a fix for this. Hopefully the current build will pass: https://travis-ci.org/github/woodem/woo/builds/748535734 and since now we will be able to test all commits in Travis.

**Comment by raviapatel** [comment] 2020-12-10 15:32
Another thing the controller seems to be lost in the new update of the code it cant be invovked from command line anymore

**Comment by eudoxos** [comment] 2020-12-10 16:06
> Another thing the controller seems to be lost in the new update of the code it cant be invoked from command line anymore

You have to compile with `-DWOO_QT5=1`, then it should work. It does here.

**Comment by raviapatel** [comment] 2020-12-10 16:18
There are two configuration error I am getting one which I previously ignored (VTK one) but it was compiling second is when I switch on -DWOO_QT5
-- The imported target "pvtk" references the file
   "/usr/bin/pvtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
CMake Error at CMakeLists.txt:175 (message):
  GLE library/headers not found

note that i am already running following command to install all dependencies 
sudo apt-get install python3-all python3-all-dev python3-numpy libeigen3-dev libhdf5-serial-dev libboost-all-dev \
         libgts-dev libtbb-dev pybind11-dev cmake cmake-data ninja-build libvtk7-dev libdouble-conversion-dev \
         libomp-7-dev python3-pip python3-future python3-prettytable python3-xlrd python3-xlwt python3-xlsxwriter\
         python3-matplotlib python3-colorama python3-genshi python3-psutil python3-pil python3-h5py python3-lockfile\
         ipython3 qt5-default

**Comment by eudoxos** [comment] 2020-12-10 16:42
It looks like you are missing [libgle3-dev](https://packages.ubuntu.com/focal/libgle3-dev). Where is the dependencies list coming from? This one should be added.

**Comment by eudoxos** [comment] 2020-12-10 17:09
The VTK warning is caused by included VTK cmake files, that must be fixed in (their) upstream.

**Comment by raviapatel** [comment] 2020-12-10 17:21
I extracted dependences from from travis configuration file. I am trying to create a simple build file which can be used again in future.

**Comment by eudoxos** [comment] 2020-12-10 18:44
Travis build without GUI on purpose, it cannot be tested headless anyway. I will try running the install script in clean 20.04 install. This should be a good inspiration for packages you need:

https://github.com/woodem/woo/blob/199488ca775df7551b059fb79dc61d4349757ed6/scripts/woo-install.py#L73-L84

**Comment by raviapatel** [comment] 2020-12-10 20:33
ok cool that you have it now in python script for installation meanwhile i managed to compile by adding library which you had said was missing. Also gui is launched however now i have another set of issues while running gui 
![image](https://user-images.githubusercontent.com/16664989/101826429-4611b780-3b2f-11eb-9917-771f8aff9119.png)

**Comment by eudoxos** [comment] 2020-12-10 20:44
I believe this was fixed a few hours back (the conversion to NodeList would happen for list but not for tuple):

https://github.com/woodem/woo/commit/199488ca775df7551b059fb79dc61d4349757ed6#diff-ccb11d6bbba0c258a0d1105779a7b536c1b65e89d6eef3322affb365bc5f9343

**Comment by eudoxos** [comment] 2020-12-14 10:20
Hi Ravi, I added `libspdlog-dev` to dependencies (unless you call cmake with `-DSPDLOG_LOCAL=ON`) so that packaged spdlog is used. This should be the last bigger infrastructure change (after removing boost::python and py2k suport).

**Comment by raviapatel** [comment] 2020-12-14 10:22
Ok I try this final build today and report to you if things are working on my side.
Thank you for your support.
regards
ravi

**Comment by raviapatel** [comment] 2020-12-17 11:38
So everything is now working fine. This is my final installation script file

sudo apt-get install python3-all python3-all-dev python3-numpy libeigen3-dev libhdf5-serial-dev libboost-all-dev\
      libgts-dev libtbb-dev pybind11-dev cmake cmake-data ninja-build libvtk7-dev libdouble-conversion-dev\
      libomp-7-dev python3-pip python3-future python3-prettytable python3-xlrd python3-xlwt python3-xlsxwriter\
      python3-matplotlib python3-colorama python3-genshi python3-psutil python3-pil python3-h5py python3-lockfile\
      ipython3 qt5-default  libgle3-dev libspdlog-dev 
pip3 install colour_runner
mkdir -p ../build
cd ../build
cmake -DWOO_FLAVOR="" -DWOO_DEBUG=OFF -DWOO_PYBIND11=ON -DWOO_VTK=ON -DWOO_HDF5=ON -DWOO_GTS=ON -DWOO_QT5=ON -DWOO_OPENMP=ON -DWOO_CCACHE=OFF -DSPDLOG_LOCAL=OFF ..
make -j 4
sudo make install

**Comment by raviapatel** [comment] 2021-04-17 18:04
is there way to force woo that it gets installed in specific folder??

**Comment by eudoxos** [comment] 2021-04-17 20:20
> is there way to force woo that it gets installed in specific folder??

Yes, create python virtual environment whereever you want, activate it and run the installation. 

Something like this (not tested, find docs on python virtual environments):
```
pip3 install virtualenv
virtualenv my/directory/venv
source my/directory/venv/bin/activate
cd somewhere/woo/scripts
./woo-install ...
```

**Comment by eudoxos** [comment] 2021-08-16 19:29
Hi Ravi, please reopen if you still have issues, I otherwise consider the problem got resolved.

**Closed by eudoxos** 2021-08-16 19:29 UTC
